### PR TITLE
No-detent support for EN16

### PR DESCRIPTION
**Pull request by warewolf**
Hey there intech studio friends; I *love* my EN16, and managed to figure out how to support encoders without detents.  Here's my code, please feel free to use this.  I disclaim any rights to this modification, please consider it public domain.

### CODE REVIEW

**Comment by SukuWc** [comment]
On the PCB there is a solder jumper labeled ND for No Detent variant of EN16. If you close that jumper you will be able to detect that you are running the No Detent hardware variant from firmware during runtime. 

You can use the grid_sys_get_hwcfg api to read the board variant, which is an 8-bit register. One of the bits in that will change from 0 to 1 after soldering the ND jumper.

I can merge the code if it uses the grid_sys_get_hwcfg based runtime branch instead of the compile time #if 0!

image
image

**Comment by warewolf** [comment]
Okay, lemme work on that.  Thanks!

**Comment by warewolf** [comment]
Okay, this cleans up the code a bit, and actually drops the use of the phase change lock variable.

**Comment by SukuWc** [comment]
All good, thanks for your contribution!

**Pull request merged**
